#################
# Edit Distance #
#################
def levenshteinDistance(seq1, seq2):
    n = len(seq1)
    m = len(seq2)
    dp = [[0] * (m+1) for _ in range(n+1)]
    for i in range(n+1):
        dp[i][0] = i
    for j in range(m+1):
        dp[0][j] = j
    for i in range(1,n+1):
        for j in range(1,m+1):
            if seq1[i-1] == seq2[j-1]:
                dp[i][j] = dp[i-1][j-1]
            else:
                dp[i][j] = min(dp[i-1][j]+1, dp[i][j-1]+1, dp[i-1][j-1]+1)
    print(end='      ')
    for j in range(m):
        print(seq2[j],end='  ')
    print('\n ', dp[0])
    for i in range(1,n+1):
        print(seq1[i-1], dp[i])
    return dp[n][m]

def main():
    print(levenshteinDistance("ORCHID","ARACHNID"))
    # print(levenshteinDistance("AQRIIDMGAFPRKHPWIIFMDMASHGCKISLYVELWFGILHKSYKPTLFEEHKIQGNPVNAGIMILSRRFCAQFQQVPIHDMTWWPTHMIFLDNKTKSHRYDERAWYEKTGNAGNDSNLEGMENVDQSSYQGGRHKSKPRKHDTYPLECEQQDGNHWMTTMSMYSNANDPDSCEQHGENCHRGRYTIAQMSHGAEHVMAMKHACLWVIMQSVLYERWRWAHRWHTTLQWRFESCSIASAKSMRTCPREAWMPVRADLWDTSGRYEYKASQSWLRNAWGLMEGGAGNKMKTDVDCSMMHKTMRYMWDSKCVPKMYCVFHQFCDHVSKQNRNNDTHILVRLGGYHKWYPSAVSKQFPKPFWPANNCFLIMLREQFRFWATRLAYQREYNWIWAADLNEVKTSFAVRLERPMMRPLGVDQDQGSYKTREWELMRMPGESNGKVQKLYQIIKLQCVRNGNRYENRKIGEPTFIQKMPGQRDTGGYYCVGVWDKDRSASEEMHAPILPIIVYDWNSHHNQAVACVRQMGNAWGCFHCELHPPWAWGVYMNILCEGWLNWDCKQWMGLCYHLPFTWRPPAMAICTMLQPNDLPQALDRAAEAEGRFEMPKAMYIKYWQKTENFCRPHRHFQITAHVMAACWSPMGKHDFSAGCVPHIWIHLWMFFEPGKPAMWERDEPHCHHIGCLDPMKDNKVYCPQIQFCACTDHVQTMFHHRNKDMFVWAVCQHENKLWPALTCFWHTAYESSGKGNADKSPHWGWWVHTIGHNFIQFFPHAHGHYRFSTNHQMHWTQPFPQRDLCYGVIAQIWDACYFGQARGIRECFDMCAVAMDLGCACGSDEHAFQPWRPGFPMNTQREWRYYISQM","ETGDQRIIDMVAFPRKRPWIIFWEMASHGCKISTCEADYRDPTDQVYFEEHKIQINPVNAGIMILRMMLCSRRFCAICVCDGQEVVKSQVTIHDMTNVCLFPEMWTMLFYGSNKTKMSVFHRYRGNEQAPYEKTGNANARDWNVSDSNLEGMERMRISSYQGGVVKSKPRKHDTYPLECEQPDGNHWMTTMSMYSNANDEQHGENCLNFHFDAQMSHGAEAPWLFVNAMYDVACLYRWRWAHRWHTTLQWRFFGQYNQEWKSCSIASMRTCPREADKNGNHMPNMADLHIRSWISYWNVSGTYEYKASQSQLRNTDVDQSMMMSQQHKCMRGFMMYAFNWWDPKMYTVFHQFCDKVRKQNRPKFWQGALNDTHILVRLGGYHKWLQGDAPSAVSVCQFPKPFWPANNNFERRGFVIMTTMWIWNEVKTSFAVRLERPMMRPLGVDQDNMANDMESYKTRWTHVSRWELMRMPGESNGKVQPIKQDQCVDNGGHTTHHNIPRRRSTWPTFIRHPGRIKMVLTAYVGDTGGYMVHEKCERHGVWDKDRSASDIQHDRKAEMHAPILPITVLDWNSHHQMCKDGWIQEFNKWQGNAWGCFHCELHFPWAWSVYRNITTARSLCEGWLNWDCKQQDWFHMGLCIQLPFTIIRPAMAGCMDCTMQCWGASWLDCENWDAAAEAERFEMPKAMYIKYAQKRDNCIAFCRPHRHFQITAHWMAACWSYMGKHGFSAGCVGDALEKKCRHIWIHLWMFFEPPKPAMKKRNERLQNTSESCYPTMVWPSVCKDNDVYCQHVQTMLHHRNKAVCQHKDNNPAMNPALHTAYESSGKGAPQDMKSPRQEAMCNIVHTIGHNPHAHGHYRFSTNHQMHWTRDLCYGLIAQIWDYCTFGQAFGIRECIHLFLGCACGSDEMAFQPWRPGFCMNTQRHPRYYISQM"))

if __name__ == "__main__":
    main()